run:
        docker run -it --rm \
                --network host \
                -v /${PWD}:/opt/gatling/user-files \
                -v /${PWD}/reports:/opt/gatling/results \
                denvazh/gatling